version: '3.7'
services:
  solr:
    container_name: ${COMPOSE_PROJECT_NAME}
    image: yusaopeny-solr:8.x
    restart: always
    volumes:
      - data:/var/solr
    labels:
      caddy: ${COMPOSE_PROJECT_NAME}.solr.ws.y.org
      caddy.reverse_proxy: "{{upstreams 8983}}"
      caddy.basicauth.solr: ${BASIC_AUTH}
    networks:
      - proxy

networks:
  proxy:
    external: true

volumes:
  data:
